name: Deploy Resource Reservation ODOO Addon

on:
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_resource_reservation:
    runs-on: ubuntu-latest
    env:
      ADDON_NAME: ${{ vars.ADDON_NAME }}
      ODOO1_ADDONS_DIR: ${{ vars.ODOO1_ADDONS_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -p 5622 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Validate Path
        shell: bash
        run: |
          if [[ ! "$ODOO1_ADDONS_DIR" =~ ^[a-zA-Z0-9_./-]+$ ]]; then
              echo "Invalid path: $ODOO1_ADDONS_DIR. Path must not contain '..' or start with '/'."
              exit 1
          fi

          if [[ "$ODOO1_ADDONS_DIR" == "/" ]] || [[ "$ODOO1_ADDONS_DIR" == *"/.."* ]]; then
              echo "Invalid path: $ODOO1_ADDONS_DIR. Path must not be the root directory or traverse upwards."
              exit 1
          fi

      - name: (Dry Run) Clean up old files
        uses: appleboy/ssh-action@v1.0.3
        env:
          ODOO1_ADDONS_DIR: ${{ vars.ODOO1_ADDONS_DIR }}
          ADDON_NAME: ${{ vars.ADDON_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: ODOO1_ADDONS_DIR,ADDON_NAME
          script: |
            if [[ ! "$ODOO1_ADDONS_DIR" =~ ^[a-zA-Z0-9_./-]+$ ]]; then
                echo "Invalid path: $ODOO1_ADDONS_DIR. Path must not contain '..' or start with '/'."
                exit 1
            fi

            if [[ "$ODOO1_ADDONS_DIR" == "/" ]] || [[ "$ODOO1_ADDONS_DIR" == *"/.."* ]]; then
                echo "Invalid path: $ODOO1_ADDONS_DIR. Path must not be the root directory or traverse upwards."
                exit 1
            fi

            echo "Uncomment the following lines to enable the cleanup"
            echo "rm -rf $ODOO1_ADDONS_DIR/$ADDON_NAME"

      - name: Generate unique dir name
        run: |
          uuid=$(uuidgen)
          echo "UUID=$uuid" >> $GITHUB_ENV

      - name: Deploy with rsync into /tmp
        shell: bash
        run: |
          rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' ./$ADDON_NAME/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/$ADDON_NAME.$UUID

      - name: (Dry Run) Copy to Odoo Addons Directory
        uses: appleboy/ssh-action@v1.0.3
        env:
          ODOO1_ADDONS_DIR: ${{ vars.ODOO1_ADDONS_DIR }}
          ADDON_NAME: ${{ vars.ADDON_NAME }}
          UUID: ${{ env.UUID }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: ODOO1_ADDONS_DIR,ADDON_NAME,UUID
          script: |
            ADDON_DIR=$ODOO1_ADDONS_DIR/$ADDON_NAME
            echo "mkdir -p $ADDON_DIR"
            echo "cp -r /tmp/$ADDON_NAME.$UUID/* $ADDON_DIR/"
